### ISSUE TITLE
Working version

### ISSUE THREAD

**Issue by arqex** [souporserious/react-interactable#3]
Hey!

I have found this repo that seems to be a port of react-native-interactable to JS. It's great I had the same idea!

I have my version already working with the same react-native-interactable API and I see you didn't update this repo for more than one year. I was wondering if you would transfer the ownership of the react-interactable NPM package to me, so I can make react-interactable public.

Cheers,
Javi

**Comment by souporserious** [comment]
Oh this sounds cool! Yeah, you can absolutely have the name 😃. What is your NPM username?

**Comment by arqex** [comment]
That's so nice, thanks very much!
My username is arqex
Here I am https://www.npmjs.com/~arqex

**Comment by souporserious** [comment]
No problem! You should be a maintainer now 😃. Excited to see what you publish!
